// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwGhFaXqR1tXcV5oiLYIdvREz3pylOK-A',
    appId: '1:215912661867:web:d042db362d28d4824dc22e',
    messagingSenderId: '215912661867',
    projectId: 'tuttilearni-54f1f',
    authDomain: 'tuttilearni-54f1f.firebaseapp.com',
    storageBucket: 'tuttilearni-54f1f.firebasestorage.app',
    measurementId: 'G-G0M5MM42LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_wFF1mJHgxvBe0P6Vl-qM8Ed1_oOAGP8',
    appId: '1:215912661867:android:bd875dda743b10934dc22e',
    messagingSenderId: '215912661867',
    projectId: 'tuttilearni-54f1f',
    storageBucket: 'tuttilearni-54f1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQHWmamNFP7EWhkRsE6wujPs2mCjaI8F0',
    appId: '1:215912661867:ios:0879299527d4dbd84dc22e',
    messagingSenderId: '215912661867',
    projectId: 'tuttilearni-54f1f',
    storageBucket: 'tuttilearni-54f1f.firebasestorage.app',
    iosBundleId: 'com.example.tuttiLearnyFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQHWmamNFP7EWhkRsE6wujPs2mCjaI8F0',
    appId: '1:215912661867:ios:0879299527d4dbd84dc22e',
    messagingSenderId: '215912661867',
    projectId: 'tuttilearni-54f1f',
    storageBucket: 'tuttilearni-54f1f.firebasestorage.app',
    iosBundleId: 'com.example.tuttiLearnyFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwGhFaXqR1tXcV5oiLYIdvREz3pylOK-A',
    appId: '1:215912661867:web:d79574fd10fb47aa4dc22e',
    messagingSenderId: '215912661867',
    projectId: 'tuttilearni-54f1f',
    authDomain: 'tuttilearni-54f1f.firebaseapp.com',
    storageBucket: 'tuttilearni-54f1f.firebasestorage.app',
    measurementId: 'G-5FK6JPQNRW',
  );

}